workerPoolSpecs:
  - machineSpec:
      machineType: n1-standard-16
      acceleratorType: NVIDIA_TESLA_P4
      acceleratorCount: 1
    replicaCount: 1
  - machineSpec:
      machineType: n1-standard-16
      acceleratorType: NVIDIA_TESLA_P4
      acceleratorCount: 1
    replicaCount: 2