workerPoolSpecs:
  - machineSpec:
      machineType: n1-standard-16
    replicaCount: 1
    containerSpec: 
      imageUri: eu.gcr.io/sandbox-michael-menzel/mnist-training:latest
      args: 
        - '--batch-size=128'
        - '--num-epochs=10'
baseOutputDirectory:
    outputUriPrefix: gs://sandbox-michael-menzel-training-europe-west4/trainings/mnist-distributed-vertex/
